FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm config set fetch-retries 5 && npm config set fetch-retry-maxtimeout 120000 && npm install --legacy-peer-deps --no-audit --progress=false

COPY . .

EXPOSE 5173
